backend/Stack/AQ/urls.py
from django.urls import path
from .views import DetailView, HomeView, CategoryList, AddReplyView, UserList, Like, SearchList

app_name = "home"

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('question/<int:q_id>/<slug:q_slug>/', DetailView.as_view(), name="detail"),
    path('question/category/<slug:slug>/', CategoryList.as_view(), name="category"),
    path('reply/<int:q_id>/<int:answer_id>/', AddReplyView.as_view(), name="reply"),
    path('user/<int:pk>/', UserList.as_view(), name="user_profile"),
    path('search/', SearchList.as_view(), name="search"),
    path('like/<int:question_id>', Like.as_view(), name="like"),
]

backend/Stack/account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import Dashboard, QuestionCreate, QuestionUpdate, QuestionDelete, Profile, Login, UserFollowView, \
    UserUnfollowView, UserRegisterView, PasswordChange

app_name = 'account'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password_change/', PasswordChange.as_view(), name='password_change'),
    # path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

urlpatterns += [
    path('', Dashboard.as_view(), name="dashboard"),
    path('question/create', QuestionCreate.as_view(), name="create"),
    path('question/update/<int:pk>', QuestionUpdate.as_view(), name="update"),
    path('question/delete/<int:pk>', QuestionDelete.as_view(), name="delete"),
    path('profile/', Profile.as_view(), name="profile"),
    path('follow/<int:pk>/', UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:pk>/', UserUnfollowView.as_view(), name='user_unfollow'),
    path('register/', UserRegisterView.as_view(), name='user_register'),
]

backend/Stack/src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('AQ.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/Stack/templates/inc/footer.html
      <div class="footer">
         <div class="container-fluid">
            <div class="col-md-5">
               <div class="footer-box">
                  <span class="title">مجله seo90</span>
                  <p>متن ساختگی با تولید سادگی نامفهوم تولید سادگی از صنعت متن ساختگی با تولید سادگی نامفهوم تولید
                     سادگی از صنعت متن ساختگی با تولید سادگی نامفهوم تولید سادگی از صنعت متن ساختگی با تولید سادگی از
                     صنعت متن ساختگی با تولید سادگی نامفهوم تولید سادگی از صنعت متن ساختگی با تولید سادگی نامفهوم
                     تولید سادگی از صنعت متن ساختگی بام تولید سادگی از صنعت متن ساختگی با تولید سادگی نامفهوم تولید
                     سادگی از صنعت متن ساختگی با تولید سادگی نامفهوم تولید سادگی از صنعت متن سادگی نامفهوم تولید
                     سادگی از صنعت
                  </p>
               </div>
            </div>
            <div class="col-md-2">
               <div class="footer-box">
                  <span class="title">دسترسی سریع</span>
                  <ul>
                     <li><a href="#">موضوعی</a></li>
                     <li><a href="#">قوانین</a></li>
                     <li><a href="#">نشریات</a></li>
                     <li><a href="#">موضوعی</a></li>
                     <li><a href="#">خبرنامه</a></li>
                  </ul>
               </div>
            </div>
            <div class="col-md-2">
               <div class="footer-box">
                  <span class="title">موضوعی</span>
                  <ul>
                     <li><a href="#">موضوعی</a></li>
                     <li><a href="#">قوانین</a></li>
                     <li><a href="#">نشریات</a></li>
                     <li><a href="#">موضوعی</a></li>
                     <li><a href="#">خبرنامه</a></li>
                  </ul>
               </div>
            </div>
            <div class="col-md-3">
               <div class="footer-box contact-box">
                  <span class="title">تماس با ما</span>
                  <p><i class="fa fa-phone"></i> 09028468446</p>
                  <p><i class="fa fa-phone"></i> 09336636892</p>
                  <p><i class="fa fa-envelope-o"></i> info@seo90.ir</p>
                  <p><i class="fa fa-map-marker"></i> تبریز </p>
               </div>
            </div>
            <div class="clear-fix"></div>
         </div>
      </div>
      <div class="end-wrapper">
         <div class="container-fluid">
            <div class="col-md-6">
               <div class="copy-r">
                  <p>&copy; تمامی حقوق متعلق به سئو 90 می باشد</p>
               </div>
            </div>
            <div class="col-md-6">
               <div class="creator text-left">
                  <p>طراحی سایت ، سئو 90</p>
               </div>
            </div>
         </div>
      </div>

backend/Stack/templates/inc/messages.html
{% if messages %}
{% for msg in messages %}
<p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
{% endfor %}
{% endif %}

backend/Stack/templates/inc/navbar.html
<div class="top-bar">
    <div class="container-fluid">
        <div class="col-md-6">
            <div class="search-btn">
                <!--                <span><i class="fa fa-search"></i></span>-->
                <form action="{% url 'home:search' %}" class="form-inline mt-3">
                    <input type="text" name="q" class="form-control" placeholder="جستوجو">
                    <button class="btn btn-warning" style="padding: 8px;border-radius: 5px;margin-right: 5px;">جستوجو
                    </button>
                </form>
            </div>
        </div>
        <div class="col-md-6">
            <div class="top-cat-box">
                <div class="col-md-12">
                    <div class="menu">
                        <ul>
                            <li><a href="{% url 'home:home' %}">خانه</a></li>
                            <li><a href="{% url 'home:home' %}">اخبار</a></li>
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'account:dashboard' %}">پنل شخصی</a></li>
                            {% endif %}
                            {% if not user.is_authenticated %}
                            <li><a href="{% url 'account:login' %}">ورود</a></li>
                            <li><a href="{% url 'account:user_register' %}">ثبت نام</a></li>
                            {% endif %}
                            <li><a href="#">تماس با ما</a></li>
                            <li><a href="#">درباره ما</a></li>
                        </ul>
                    </div>
                </div>
                <!-- <div class="col-md-3">
                   <div class="show-cat">
                       <span>
                           دسته ها
                           <i class="fa fa-bars"></i>
                       </span>
                   </div>
                   </div> -->
            </div>
        </div>
    </div>
</div>
<div class="main-header">
    <div class="container-fluid">
        <div class="col-md-10">
            <div class="main-menu">
                <ul>
                    {% for cat in AllCategory %}
                    <li><a href="{% url 'home:category' cat.slug %}">{{ cat.title }}</a></li>
                    {% endfor %}
                </ul>

            </div>
        </div>
        <div class="col-md-2">
            <div class="social-box">
                <ul>
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>