backend/Stack/AQ/urls.py
from django.urls import path
from .views import DetailView, HomeView, CategoryList, AddReplyView, UserList, Like, SearchList

app_name = "home"

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('question/<int:q_id>/<slug:q_slug>/', DetailView.as_view(), name="detail"),
    path('question/category/<slug:slug>/', CategoryList.as_view(), name="category"),
    path('reply/<int:q_id>/<int:answer_id>/', AddReplyView.as_view(), name="reply"),
    path('user/<int:pk>/', UserList.as_view(), name="user_profile"),
    path('search/', SearchList.as_view(), name="search"),
    path('like/<int:question_id>', Like.as_view(), name="like"),
]

backend/Stack/account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import Dashboard, QuestionCreate, QuestionUpdate, QuestionDelete, Profile, Login, UserFollowView, \
    UserUnfollowView, UserRegisterView, PasswordChange

app_name = 'account'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password_change/', PasswordChange.as_view(), name='password_change'),
    # path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

urlpatterns += [
    path('', Dashboard.as_view(), name="dashboard"),
    path('question/create', QuestionCreate.as_view(), name="create"),
    path('question/update/<int:pk>', QuestionUpdate.as_view(), name="update"),
    path('question/delete/<int:pk>', QuestionDelete.as_view(), name="delete"),
    path('profile/', Profile.as_view(), name="profile"),
    path('follow/<int:pk>/', UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:pk>/', UserUnfollowView.as_view(), name='user_unfollow'),
    path('register/', UserRegisterView.as_view(), name='user_register'),
]

backend/Stack/src/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('AQ.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    # add root static files
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # add media static files
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/Stack/AQ/models.py
from django.db import models
from account.models import User
from django.urls import reverse
from django.utils.text import slugify
from ckeditor.fields import RichTextField


# Create your models here.

class Sliders(models.Model):
    image = models.ImageField(default='1.jpg', verbose_name="تصویر")
    title = models.CharField(max_length=200, verbose_name="عنوان")
    created = models.DateTimeField(auto_now_add=True, verbose_name="زمان ساخت")

    class Meta:
        verbose_name = "اسلایدر"
        verbose_name_plural = "اسلایدرز"
        ordering = ['created']


class Category(models.Model):
    title = models.CharField(max_length=200, verbose_name="عنوان")
    slug = models.SlugField(max_length=200, unique=True, verbose_name="ادرس")
    status = models.BooleanField(
        default=True, verbose_name="ایا نمایش داده شود؟")
    position = models.IntegerField(default=0, verbose_name="پوزیشن")

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"
        ordering = ['position']

    def __str__(self):
        return self.title

    def get_absolute_url_cat(self):
        return reverse('home:category', args=(self.slug))


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='questions', verbose_name="کاربر")
    title = models.CharField(max_length=200, verbose_name="عنوان سوال")
    slug = models.SlugField(max_length=200, verbose_name="ادرس")
    category = models.ManyToManyField(Category, related_name="questions", verbose_name="دسته بندی")
    body = RichTextField(blank=True, null=True, verbose_name="متن سوال")
    # body = models.TextField()
    image = models.ImageField(default='1.jpg', verbose_name="تصویر")
    created = models.DateTimeField(auto_now_add=True, verbose_name="زمان ساخت")

    class Meta:
        verbose_name = "سوال"
        verbose_name_plural = "سوال ها"
        ordering = ['created']

    def __str__(self):
        return f'{self.user} - {self.title[:20]}'

    def category_to_str(self):
        return "، ".join([category.title for category in self.category.all()])

    category_to_str.short_description = "دسته‌بندی"

    def get_absolute_url(self):
        return reverse('home:detail', args=(self.id, self.slug))
        return reverse('account:dashboard')

    def like_count(self):
        return self.Qvotes.count()

    def user_can_like(self, user):
        user_like = user.uvotes.filter(question=self)
        if user_like.exists():
            return True
        return False


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uanswer', verbose_name="کاربر")
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='panswers',
                                 verbose_name="جواب به سوال")
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='ranswers', blank=True, null=True,
                              verbose_name="پاسخ")
    is_reply = models.BooleanField(default=False, verbose_name="پاسخ داده شده؟")
    body = RichTextField(blank=True, null=True, verbose_name="متن جواب")
    created = models.DateTimeField(auto_now_add=True, verbose_name="زمان ساخت")

    class Meta:
        verbose_name = "جواب"
        verbose_name_plural = "جواب ها"
        ordering = ['created']

    def __str__(self):
        return f'{self.user} - {self.body[:20]}'


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uvotes', verbose_name="کاربر")
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='Qvotes', verbose_name="سوال")

    class Meta:
        verbose_name = "لایک"
        verbose_name_plural = "لایک ها"

    def __str__(self):
        return f'{self.user} liked {self.question.slug}'

backend/Stack/AQ/forms.py
from django import forms
from .models import Answer


class AnswerCreateForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }


class AnswerReplyForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }

backend/Stack/AQ/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView
from django.core.paginator import Paginator
from .forms import AnswerCreateForm, AnswerReplyForm
from .models import Question, Category, Answer, Vote, Sliders
from django.contrib.auth.mixins import LoginRequiredMixin
from account.models import User, Relation
from django.db.models import Q


# Create your views here.


class HomeView(ListView):
    template_name = 'AQ/home.html'
    queryset = Question.objects.all()
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['AllCategory'] = Category.objects.all()
        context['sliders'] = Sliders.objects.all()
        return context


class DetailView(View):
    form_class = AnswerCreateForm
    form_class_reply = AnswerReplyForm

    def setup(self, request, *args, **kwargs):
        self.question_instance = get_object_or_404(Question, pk=kwargs['q_id'], slug=kwargs['q_slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        answers = self.question_instance.panswers.filter(is_reply=False)
        can_like = False
        if request.user.is_authenticated and self.question_instance.user_can_like(request.user):
            can_like = True
        return render(request, 'AQ/detail.html',
                      {'question': self.question_instance, 'answers': answers, 'form': self.form_class,
                       'reply_form': self.form_class_reply, 'can_like': can_like})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_answer = form.save(commit=False)
            new_answer.user = request.user
            new_answer.question = self.question_instance
            new_answer.save()
            return redirect('home:detail', self.question_instance.id, self.question_instance.slug)


class CategoryList(ListView):
    paginate_by = 6
    template_name = 'AQ/category_list.html'
    model = Category

    def get_queryset(self):
        global category
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.all(), slug=slug)
        return category.questions.all()

    def get_context_data(self, **kwargs):
        context = super(CategoryList, self).get_context_data(**kwargs)
        context['AllCategory'] = Category.objects.all()
        return context


class AddReplyView(LoginRequiredMixin, View):
    form_class = AnswerReplyForm

    def post(self, request, q_id, answer_id):
        question = get_object_or_404(Question, id=q_id)
        answer = get_object_or_404(Answer, id=answer_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.question = question
            reply.reply = answer
            reply.is_reply = True
            reply.save()
        return redirect('home:detail', question.id, question.slug)


class UserList(LoginRequiredMixin, ListView):
    def get(self, request, pk):
        is_following = False
        user = get_object_or_404(User, pk=pk)
        questions = user.questions.all()
        relation = Relation.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            is_following = True
        return render(request, 'AQ/user_list.html',
                      {'user': user, 'questions': questions, 'is_following': is_following})


class Like(LoginRequiredMixin, View):
    def get(self, request, question_id):
        question = get_object_or_404(Question, id=question_id)
        like = Vote.objects.filter(question=question, user=request.user)
        if like.exists():
            messages.error(request, 'you have already liked this question', 'danger')
        else:
            Vote.objects.create(question=question, user=request.user)
            messages.success(request, 'you liked this question', 'success')
        return redirect('home:detail', question.id, question.slug)


class SearchList(ListView):
    paginate_by = 5
    template_name = 'AQ/search_ist.html'

    def get_queryset(self):
        search = self.request.GET.get('q')
        return Question.objects.filter(Q(body__icontains=search) | Q(title__icontains=search))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.request.GET.get('q')
        return context

# class SliderView(ListView):
#     template_name = 'AQ/include_sliders.html'
#     queryset = Sliders.objects.all()
#     context_object_name = 'sliders'

# def sliders(request):
#     slider_list = Sliders.objects.all()
#     context = {
#         "slider_list": slider_list
#     }
#     return render(request, 'AQ/home.html', context)

backend/Stack/AQ/templates/AQ/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="latest-posts">
    <div class="container-fluid">
        <div class="col-md-9">
            <div class="blog-title-span">
                <span class="title">{{ AllCategory.title }}</span>
            </div>
            {% for question in object_list %}
            <div class="col-md-4">
                <div class="post-box">
                    <a href="{{ question.get_absolute_url }}">
                        <figure>
                            <img src="{{ question.image.url }}" alt="">
                            <figcaption class="meta-fig">
                                <span><i class="fa fa-clock-o"></i> {{ question.created |date:"Y-M" }}</span>&nbsp;
                                <!--                              <span><i class="fa fa-comment-o"></i> 12</span>-->
                            </figcaption>
                            <figcaption class="view">
                                {% for cat in question.category.all %}
                                <span>{{ cat.title }}</span>
                                {% endfor %}
                            </figcaption>
                        </figure>
                        <div class="text-p">
                            <!--                           <h5>چگونه از اشخاص مطالبی که دوست نداریم دوری کنیم ؟</h5>-->
                            <p>{{ question.body | striptags|truncatewords:23 }}</p>
                            <div class="text-rigt">
                                <a href="{{ question.get_absolute_url }}">ادامه ...</a></div>
                        </div>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-md-3 main-content">
            <div class="l-sidebar">
                <div class="cat-sidebar">
                    <span class="title">دسته بندی مطالب</span>
                    <div class="text-left"><i class="fa fa-folder-o"></i></div>
                    <ul>
                        {% for cat in AllCategory %}
                        <li><a href="{% url 'home:category' cat.slug %}">{{ cat.title }}</a><span>{{ object_list.count }}</span>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="top-sidebar-r">
                <span class="title">عکس</span>
                <a href="#">
                    <div class="bx">
                        <div class="col-md-6">
                            <div class="img-box">
                                <figure>
                                    <img src="img/parsitarh-1038x515.png" alt="">
                                    <figcaption><span>4</span></figcaption>
                                </figure>
                            </div>
                        </div>
                        <div class="col-md-6 ">
                            <div class="meta">
                                <h5>
                                    عنوان برای متن ارسال شده</h6>
                                    <span><i class="fa fa-clock-o"></i> 99/3/20</span>
                                    <div class="text-left">
                                        <sub><i class="fa fa-comment"></i> 246</sub>
                                    </div>
                            </div>
                        </div>
                    </div>
                </a>
                <a href="#">
                    <div class="bx">
                        <div class="col-md-6">
                            <div class="img-box">
                                <figure>
                                    <img src="img/1733753707Capture.png" alt="">
                                    <figcaption><span>2</span></figcaption>
                                </figure>
                            </div>
                        </div>
                        <div class="col-md-6 ">
                            <div class="meta">
                                <h5>
                                    لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان
                                    گرافیک است. چاپگرها و... متن ارسال شده</h6>
                                    <span><i class="fa fa-clock-o"></i> 99/3/20</span>
                                    <div class="text-left">
                                        <sub><i class="fa fa-comment"></i> 26</sub>
                                    </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <br>


        </div>
        <div class="col-md-12 text-center">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">قبلی</a>
                    </li>
                    {% endif %}
                    {% for page in paginator.page_range %}
                    <li class="page-item"><a class="page-link" href="?page= {{ page }}">{{ page }}</a></li>
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">بعدی</a>
                    </li>
                    {% endif %}

                </ul>
            </nav>
        </div>
    </div>
</div>
<div class="clear-fix"></div>
{% endblock %}

backend/Stack/AQ/templates/AQ/detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block content %}
<div class="single_post">
    <div class="container-fluid">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    <div class="post_img">
                        <img src="{{ question.image.url }}" alt="">
                    </div>
                </div>
                <div class="col-md-2"></div>
            </div>
            <div class="posts_meta text-center">
                <!--                  <span><i class="fa fa-comment-o"></i> 25 نظر</span>-->
                <span><i class="fa fa-archive"></i> اقتصادی</span>
                <span><i class="fa fa-comment"></i> {{answers.count}} پاسخ</span>
                <span><i class="fa fa-user"></i><a href="{% url 'home:user_profile' question.user_id %}"
                                                   style="color: #999"> {{question.user.get_full_name}} </a></span>
                <span><i class="fa fa-calendar"></i> {{ question.created |date:"Y-M" }}</span>
            </div>

            <div class="post_content">
                <h4>{{ question.title }}</h4>
                <p>{{ question.body|safe }}</p>
                <a href="{% url 'home:like' question.id %}" class="{% if can_like %} disabled {% endif %} btn btn-danger btn-block">
                    Like {{ question.like_count }}
                </a>
            </div>

            {% if user.is_authenticated %}
            <div class="comments_form">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        {{form.as_p}}
                        {{form.media}}
                        <div class="col-md-12">
                            <div class="text-left">
                                <button class="btn btn-primary">ثبت پاسخ</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            {% else %}
            <p class="alert alert-danger" role="alert">لطفا <a class="alert-link"
                                                               href="{% url 'account:login' %}">وارد</a> حساب کاربری خود
                شوید.</p>
            {% endif %}


            {% for answer in answers %}
            <div class="comments_form">
                <label>زمان پاسخ : {{answer.created|timesince}}</label>
                <form>
                    <div class="form-row">
                        <div class="col-md-6">
                            <label>نام کاربر :<a href="{% url 'home:user_profile' user.pk %}"> {{ answer.user.get_full_name }}</a></label>
                        </div>
                        <div class="col-md-12">
                            <p>{{ answer.body | striptags }}</p>
                        </div>


                        <!--                        {% if request.user.is_authenticated %}-->
                        <!--                        <div class="comments_form">-->
                        <!--                            <form action="{% url 'home:reply' question.id answer.id %}" method="post">-->
                        <!--                                {% csrf_token %}-->
                        <!--                                <div class="form-row">-->
                        <!--                                    {{reply_form.as_p}}-->
                        <!--                                    &lt;!&ndash;                                    {{reply_form.media}}&ndash;&gt;-->
                        <!--                                    <div class="col-md-12">-->
                        <!--                                        <div class="text-left">-->
                        <!--                                            <button class="btn btn-primary">ثبت پاسخ</button>-->
                        <!--                                        </div>-->
                        <!--                                    </div>-->
                        <!--                                </div>-->
                        <!--                            </form>-->
                        <!--                        </div>-->
                        <!--                        {% endif %}-->

                        {% with replies=answer.ranswers.all %}
                        {% for reply in replies %}
                        <div class="col-md-12">
                            <p>نام کاربر : {{ reply.user }} <br>{{ reply.body | striptags }}</p>
                        </div>
                        {% endfor %}
                        {% endwith %}
                    </div>
                </form>
                {% empty %}
                <h4 class="jumbotron">پاسخی هنوز ثبت نشده است ...</h4>
            </div>
            {% endfor %}
            </form>
        </div>
    </div>
</div>
</div>

<script>
    function myFunction(x) {
  x.classList.toggle("fa-thumbs-down");
}


</script>
{% endblock %}

backend/Stack/AQ/templates/AQ/question_confirm_delete.html
{% extends 'registration/base_admin.html' %}

{% block admin_content %}
<div class="col-md-8 text-center mx-auto">
    <div class="card card-danger">
        <div class="card-header">
            <h3 class="card-title mb-0 float-left">حذف سوال</h3>
        </div>
        <div class="card-body py-4">

            <form method="post">
                {% csrf_token %}
                <p class="py-2">آیا از حذف سوال
                    {{ object }}
                    مطمعن هستید؟</p>
                <input class="btn btn-danger" type="submit" value="حذف"></form>
        </div>
    </div>
</div>
{% endblock %}

backend/Stack/AQ/templates/AQ/search_ist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="latest-posts">
    <div class="container-fluid">
        <div class="col-md-12">
            <div class="blog-title-span">
                <span class="title"> جستوجو : {{ search }}</span>
            </div>

            {% for question in object_list %}
            <div class="col-md-4">
                <div class="post-box">
                    <a href="{{ question.get_absolute_url }}">
                        <figure>
                            <img src="{{ question.image.url }}" alt="">
                            <figcaption class="meta-fig">
                                <span><i class="fa fa-clock-o"></i> {{ question.created |date:"Y-M" }}</span>&nbsp;
                                <!--                              <span><i class="fa fa-comment-o"></i> 12</span>-->
                            </figcaption>
                            <figcaption class="view">
                                {% for cat in question.category.all %}
                                <span>{{ cat.title }}</span>
                                {% endfor %}
                            </figcaption>
                        </figure>
                        <div class="text-p">
                            <!--                           <h5>چگونه از اشخاص مطالبی که دوست نداریم دوری کنیم ؟</h5>-->
                            <p>{{ question.body | striptags|truncatewords:23 }}</p>
                            <div class="text-rigt">
                                <a href="{{ question.get_absolute_url }}">ادامه ...</a></div>
                        </div>
                    </a>
                </div>
            </div>
            {% empty %}
            <h4 class="jumbotron">متاسفانه موردی برای نمایش وجود ندارد ...</h4>
            {% endfor %}
        </div>

        <div class="col-md-12 text-center">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item"><a class="page-link" href="#">قبلی</a></li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item"><a class="page-link" href="#">بعدی</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>
<div class="clear-fix"></div>
{% endblock %}

backend/Stack/AQ/templates/AQ/user_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="latest-posts">
    <div class="container-fluid">
        <div class="col-md-12">
            <div class="blog-title-span">
                <span class="title">{{ user.get_full_name }}</span>
            </div>

            {% if request.user.id != user.id and not is_following %}
            <a class="btn btn-primary" href="{% url 'account:user_follow' user.id %}">Follow</a>
            {% elif request.user.id != user.id and is_following %}
            <a class="btn btn-primary" href="{% url 'account:user_unfollow' user.id %}">Unfollow</a>
            {% endif %}

            {% for question in questions %}
            <div class="col-md-4">
                <div class="post-box">
                    <a href="{{ question.get_absolute_url }}">
                        <figure>
                            <img src="{{ question.image.url }}" alt="">
                            <figcaption class="meta-fig">
                                <span><i class="fa fa-clock-o"></i> {{ question.created |date:"Y-M" }}</span>&nbsp;
                                <!--                              <span><i class="fa fa-comment-o"></i> 12</span>-->
                            </figcaption>
                            <figcaption class="view">
                                {% for cat in question.category.all %}
                                <span>{{ cat.title }}</span>
                                {% endfor %}
                            </figcaption>
                        </figure>
                        <div class="text-p">
                            <!--                           <h5>چگونه از اشخاص مطالبی که دوست نداریم دوری کنیم ؟</h5>-->
                            <p>{{ question.body | striptags|truncatewords:23 }}</p>
                            <div class="text-rigt">
                                <a href="{{ question.get_absolute_url }}">ادامه ...</a></div>
                        </div>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="col-md-12 text-center">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item"><a class="page-link" href="#">قبلی</a></li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item"><a class="page-link" href="#">بعدی</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>
<div class="clear-fix"></div>
{% endblock %}